export const diplomasData = [
  { title: 'React Avanzado', href: '/Diplomas/diploma-react-avanzado.pdf' },
  { title: 'React con TypeScript', href: '/Diplomas/diploma-react-typescript.pdf' },
  { title: 'TypeScript', href: '/Diplomas/diploma-typescript-22.pdf' },
  { title: 'React SSR', href: '/Diplomas/diploma-react-ssr.pdf' },
  { title: 'React Redux Profesional', href: '/Diplomas/diploma-react-redux-profesional.pdf' },
  { title: 'Supabase', href: '/Diplomas/diploma-supabase.pdf' },
  { title: 'React Patrones Render', href: '/Diplomas/diploma-react-patrones-render.pdf' },
  { title: 'React Router', href: '/Diplomas/diploma-react-router.pdf' },
  { title: 'React State Machine', href: '/Diplomas/diploma-react-state-machines.pdf' },
  { title: 'Vite js', href: '/Diplomas/diploma-vitejs.pdf' },
  { title: 'Frontend Developer Practico', href: '/Diplomas/diploma-frontend-developer-practico.pdf' },
  { title: 'Frontend Developer', href: '/Diplomas/diploma-frontend-developer.pdf' },
  { title: 'Web Components JS', href: '/Diplomas/diploma-web-components-javascript.pdf' },
  { title: 'Django Rest Framework', href: '/Diplomas/diploma-django-rest-framework.pdf' },
  { title: 'Django', href: '/Diplomas/diploma-django.pdf' },
  { title: 'Python', href: '/Diplomas/diploma-python.pdf' },
  { title: 'POO JS', href: '/Diplomas/diploma-javascript-poo.pdf' },
  { title: 'Asincronismo con JavaScript', href: '/Diplomas/diploma-asincronismo-js.pdf' },
  { title: 'EscmaScript 6', href: '/Diplomas/diploma-ecmascript-6.pdf' },
  { title: 'React', href: '/Diplomas/diploma-react.pdf' },
  { title: 'React practico', href: '/Diplomas/diploma-react-vite-tailwindcss.pdf' },
  { title: 'Tailwind CSS', href: '/Diplomas/diploma-react-webpack-sass.pdf' },
  { title: 'Git y Github', href: '/Diplomas/diploma-git-github.pdf' },
  { title: 'Webpack', href: '/Diplomas/diploma-webpack.pdf' },
  { title: 'API Profesional', href: '/Diplomas/diploma-api-profesional.pdf' },
  { title: 'API Practico', href: '/Diplomas/diploma-api-practico.pdf' },
  { title: 'SPA JavaScript', href: '/Diplomas/diploma-spa-javascript.pdf' },
  { title: 'TypeScript Tipos Avanzados', href: '/Diplomas/diploma-typescript-tipos-avanzados.pdf' },
  { title: 'POO TypeScript', href: '/Diplomas/diploma-typescript-poo.pdf' },
  { title: 'Patrones de Diseño', href: '/Diplomas/diploma-patrones-diseno-software.pdf' },
  { title: 'IA Data ML', href: '/Diplomas/diploma-ia-data-ml-2023.pdf' },
  { title: 'Vision Artificial', href: '/Diplomas/diploma-vision-artificial.pdf' },
  { title: 'TensorFlow.js', href: '/Diplomas/diploma-tensorflow-js.pdf' },
  { title: 'DeepLearning', href: '/Diplomas/diploma-deeplearning.pdf' },
  { title: 'IA Devs', href: '/Diplomas/diploma-ia-devs.pdf' },
  { title: 'Unit Testing Python', href: '/Diplomas/diploma-unit-testing-python.pdf' },
  { title: 'Python Funciones', href: '/Diplomas/diploma-python-funciones.pdf' },
  { title: 'Python PIP', href: '/Diplomas/diploma-python-pip.pdf' },
  { title: 'Fundamentos DB', href: '/Diplomas/diploma-fundamentos-db.pdf' },
  { title: 'Introduccion al Backend', href: '/Diplomas/diploma-backend.pdf' },
  { title: 'Mobile First', href: '/Diplomas/diploma-mobile-first.pdf' },
  { title: 'HTML Practico', href: '/Diplomas/diploma-html-practico.pdf' },
  { title: 'HTML y CSS', href: '/Diplomas/diploma-html-css-2020.pdf' },
  { title: 'Manipulación de Arrays', href: '/Diplomas/diploma-arrays.pdf' },
  { title: 'Manipulacion del DOM', href: '/Diplomas/diploma-dom.pdf' },
  { title: 'Animaciones CSS', href: '/Diplomas/diploma-animaciones-css-practico.pdf' },
  { title: 'Devtools', href: '/Diplomas/diploma-devtools.pdf' },
  { title: 'Basico JS', href: '/Diplomas/diploma-basico-javascript.pdf' },
  { title: 'Programacion Basica', href: '/Diplomas/diploma-programacion-basica.pdf' },
  { title: 'Pensamiento Logico', href: '/Diplomas/diploma-pensamiento-logico-2022.pdf' },
  { title: 'Pensamiento Logico Estructuras', href: '/Diplomas/diploma-pensamiento-logico-estructuras-2022.pdf' },
  { title: 'Pensamiento Logico Lenguajes', href: '/Diplomas/diploma-pensamiento-logico-lenguajes-2022.pdf' },
  { title: 'Configuraciones Windows', href: '/Diplomas/diploma-configuracion-windows.pdf' },
  { title: 'Prework Windows', href: '/Diplomas/diploma-prework-windows.pdf' },
  { title: 'Terminal', href: '/Diplomas/diploma-terminal-21.pdf' },
  { title: 'NPM', href: '/Diplomas/diploma-npm.pdf' },
  { title: 'N8N', href: '/Diplomas/diploma-n8n.pdf' },
  { title: 'Astro', href: '/Diplomas/diploma-astro.pdf' },
  { title: 'WebScraping', href: '/Diplomas/diploma-webscraping.pdf' },
];
